server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql:///heima?useSSL=false
    username: root
    password: warrior_520
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.block: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.block.elasticsearch